### ISSUE TITLE
Could you update the `v1` tag to point at latest release?

### ISSUE THREAD

**Issue by mondeja** [ngalaiko/setup-hledger#3]
Additionally, it seems that the `v1.34.0` tag and changelog entry is not accurate because now it supports up to v1.40.

**Comment by ngalaiko** [comment]
done! thanks for mentioning this, i should really document this process

**Comment by ngalaiko** [comment]
https://github.com/ngalaiko/setup-hledger/commit/21e4bfab5c2684ba72252cfab09b0ae7c34349d0
https://github.com/ngalaiko/setup-hledger/releases/tag/v1.40.0
